-- 1) Master list of contracts
create table if not exists public.contracts (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  sector text not null default 'Unknown',
  cftc_code text,
  first_date date,
  last_date date
);

-- 2) Raw weekly values from CFTC
create table if not exists public.cot_weekly (
  id bigint generated by default as identity primary key,
  contract_id uuid references public.contracts(id) on delete cascade,
  report_date date not null,
  prod_class text,
  comm_long int,
  comm_short int,
  ls_long int,
  ls_short int,
  ss_long int,
  ss_short int,
  open_interest int,
  unique (contract_id, report_date)
);

-- 3) Derived metrics
create table if not exists public.cot_metrics (
  id bigint generated by default as identity primary key,
  contract_id uuid references public.contracts(id) on delete cascade,
  report_date date not null,
  comm_net int,
  ls_net int,
  ss_net int,
  comm_index numeric(5,2),
  ls_index numeric(5,2),
  ss_index numeric(5,2),
  wow_comm_delta int,
  wow_ls_delta int,
  wow_ss_delta int,
  unique (contract_id, report_date)
);

-- 4) Refresh log
create table if not exists public.refresh_log (
  id bigint generated by default as identity primary key,
  run_at timestamptz default now(),
  rows_inserted int,
  rows_updated int,
  error text
);

-- Convenience view: latest week only
create or replace view public.cot_latest as
select *
from cot_metrics
where report_date = (select max(report_date) from cot_metrics);

-- Enable RLS (optional - disable if public read access is fine)
-- alter table public.contracts enable row level security;
-- alter table public.cot_weekly enable row level security;
-- alter table public.cot_metrics enable row level security;
-- alter table public.refresh_log enable row level security;

-- Create policies for anon access (uncomment if RLS enabled)
-- create policy "Allow anon read contracts" on public.contracts for select using (true);
-- create policy "Allow anon read cot_weekly" on public.cot_weekly for select using (true);
-- create policy "Allow anon read cot_metrics" on public.cot_metrics for select using (true);
-- create policy "Allow anon read refresh_log" on public.refresh_log for select using (true);